In [1]:
import torch
import torch.nn as nn

def rbf_kernel(x):
    gamma = 1.0  # Gamma is the inverse of the variance; adjust it as needed
    x_norm = (x**2).sum(1).view(-1, 1)
    print(x_norm)
    x_prod = torch.mm(x, x.t())
    print(x_prod)
    print(x_norm.t())
    rbf = torch.exp(-gamma * (x_norm + x_norm.t() - 2 * x_prod))
    return rbf

sample = torch.randn(5, 10)
rbf = rbf_kernel(sample)
print(rbf)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
tensor([[10.9056],
        [11.3658],
        [17.7271],
        [ 8.1200],
        [ 3.0216]])
tensor([[10.9056,  7.2064,  3.9120,  1.8940,  0.2785],
        [ 7.2064, 11.3658,  3.2966, -3.9080,  2.0720],
        [ 3.9120,  3.2966, 17.7271,  0.4083,  0.4300],
        [ 1.8940, -3.9080,  0.4083,  8.1200, -0.9674],
        [ 0.2785,  2.0720,  0.4300, -0.9674,  3.0216]])
tensor([[10.9056, 11.3658, 17.7271,  8.1200,  3.0216]])
tensor([[1.0000e+00, 3.8642e-04, 9.1804e-10, 2.4120e-07, 1.5609e-06],
  

In [14]:
rbf.shape

torch.Size([5, 5])

In [12]:
print(sample[0])

tensor([ 0.7565, -0.4134])
